-- Create tables for PostgreSQL backend

-- NL2SQL_USERS table
CREATE TABLE IF NOT EXISTS "NL2SQL_USERS" (
  "ID" SERIAL PRIMARY KEY,
  "EMAIL" VARCHAR(255) NOT NULL UNIQUE,
  "PASSWORD" VARCHAR(255) NOT NULL,
  "NAME" VARCHAR(255),
  "IS_VERIFIED" BOOLEAN DEFAULT FALSE,
  "VERIFICATION_TOKEN" VARCHAR(255),
  "VERIFICATION_EXPIRES" TIMESTAMP,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ORG_ID" INTEGER,
  "ROLE" VARCHAR(50),
  "EXPERIENCE_LEVEL" VARCHAR(50),
  "INTERESTS" TEXT,
  "NOTIFICATIONS_ENABLED" BOOLEAN DEFAULT TRUE,
  "HAS_COMPLETED_ONBOARDING" BOOLEAN DEFAULT FALSE,
  "TOKEN_EXPIRY" TIMESTAMP
);

-- NL2SQL_SAVED_DASHBOARDS table
CREATE TABLE IF NOT EXISTS "NL2SQL_SAVED_DASHBOARDS" (
  "DASHBOARD_UUID" VARCHAR(255) PRIMARY KEY,
  "ORG_ID" INTEGER NOT NULL,
  "USER_ID" INTEGER NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "DASHBOARD_NAME" VARCHAR(255),
  "DASHBOARD_CONFIG" JSONB,
  FOREIGN KEY ("ORG_ID") REFERENCES "NL2SQL_ORG"("ORG_ID"),
  FOREIGN KEY ("USER_ID") REFERENCES "NL2SQL_USERS"("ID")
);

-- NL2SQL_ORG table
CREATE TABLE IF NOT EXISTS "NL2SQL_ORG" (
  "ORG_ID" SERIAL PRIMARY KEY,
  "ORG_NAME" VARCHAR(255) NOT NULL,
  "ORG_STATUS" CHAR(1) DEFAULT 'Y',
  "DATABASE_TYPE" VARCHAR(50),
  "DATABASE_INFO" TEXT,
  "DATABASE_OBJECTS" BYTEA,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- NL2SQL_DATABASE_TYPE table
CREATE TABLE IF NOT EXISTS "NL2SQL_DATABASE_TYPE" (
  "TYPE_ID" SERIAL PRIMARY KEY,
  "DB_NAME" VARCHAR(50) NOT NULL,
  "DB_STATUS" CHAR(1) DEFAULT 'Y'
);

-- NL2SQL_AVAILABLE_TABLES table
CREATE TABLE IF NOT EXISTS "NL2SQL_AVAILABLE_TABLES" (
  "ID" SERIAL PRIMARY KEY,
  "ORG_ID" INTEGER NOT NULL,
  "TABLE_NAME" VARCHAR(255) NOT NULL,
  "TABLE_DESCRIPTION" TEXT,
  "IS_ACTIVE" CHAR(1) DEFAULT 'Y',
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ORG_ID") REFERENCES "NL2SQL_ORG"("ORG_ID")
);

-- NL2SQL_TABLE_COLUMNS table
CREATE TABLE IF NOT EXISTS "NL2SQL_TABLE_COLUMNS" (
  "ID" SERIAL PRIMARY KEY,
  "TABLE_ID" INTEGER NOT NULL,
  "COLUMN_NAME" VARCHAR(255) NOT NULL,
  "COLUMN_TYPE" VARCHAR(50),
  "COLUMN_DESCRIPTION" TEXT,
  "IS_SEARCHABLE" CHAR(1) DEFAULT 'Y',
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("TABLE_ID") REFERENCES "NL2SQL_AVAILABLE_TABLES"("ID")
);

-- NL2SQL_QUERIES table
CREATE TABLE IF NOT EXISTS "NL2SQL_QUERIES" (
  "ID" SERIAL PRIMARY KEY,
  "ORG_ID" INTEGER NOT NULL,
  "USER_ID" INTEGER NOT NULL,
  "QUERY_TEXT" TEXT NOT NULL,
  "SQL_GENERATED" TEXT,
  "EXECUTION_STATUS" VARCHAR(50),
  "ERROR_MESSAGE" TEXT,
  "EXECUTION_TIME" FLOAT,
  "EXECUTION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ROWS_RETURNED" INTEGER,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ORG_ID") REFERENCES "NL2SQL_ORG"("ORG_ID"),
  FOREIGN KEY ("USER_ID") REFERENCES "NL2SQL_USERS"("ID")
);

-- NL2SQL_QUERY_PERFORMANCE table
CREATE TABLE IF NOT EXISTS "NL2SQL_QUERY_PERFORMANCE" (
  "ID" SERIAL PRIMARY KEY,
  "ORG_ID" INTEGER NOT NULL,
  "DATE_PERIOD" VARCHAR(50),
  "PERIOD_TYPE" VARCHAR(20),
  "TOTAL_QUERIES" INTEGER DEFAULT 0,
  "SUCCESSFUL_QUERIES" INTEGER DEFAULT 0,
  "FAILED_QUERIES" INTEGER DEFAULT 0,
  "AVG_EXECUTION_TIME" FLOAT DEFAULT 0,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ORG_ID") REFERENCES "NL2SQL_ORG"("ORG_ID")
);

-- NL2SQL_USER_ACTIVITY table
CREATE TABLE IF NOT EXISTS "NL2SQL_USER_ACTIVITY" (
  "ID" SERIAL PRIMARY KEY,
  "USER_ID" INTEGER NOT NULL,
  "ORG_ID" INTEGER NOT NULL,
  "ACTIVITY_TYPE" VARCHAR(50),
  "ACTIVITY_DETAILS" TEXT,
  "IP_ADDRESS" VARCHAR(50),
  "USER_AGENT" TEXT,
  "ACTIVITY_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("USER_ID") REFERENCES "NL2SQL_USERS"("ID"),
  FOREIGN KEY ("ORG_ID") REFERENCES "NL2SQL_ORG"("ORG_ID")
);

-- NL2SQL_PLANS table
CREATE TABLE IF NOT EXISTS "nl2sql_plans" (
  "id" SERIAL PRIMARY KEY,
  "plan_name" VARCHAR(100) NOT NULL,
  "plan_description" TEXT,
  "price_monthly" NUMERIC(10, 2),
  "price_yearly" NUMERIC(10, 2),
  "is_active" BOOLEAN DEFAULT TRUE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "is_free" BOOLEAN DEFAULT FALSE
);

-- NL2SQL_PLANS_FEATURES table
CREATE TABLE IF NOT EXISTS "nl2sql_plans_features" (
  "id" SERIAL PRIMARY KEY,
  "plan_id" INTEGER NOT NULL,
  "feature_key" VARCHAR(100) NOT NULL,
  "value_num" NUMERIC(10, 2),
  "value_text" TEXT,
  "value_flag" BOOLEAN,
  "is_active" BOOLEAN DEFAULT TRUE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("plan_id") REFERENCES "nl2sql_plans"("id")
);

-- Insert default database types
INSERT INTO "NL2SQL_DATABASE_TYPE" ("DB_NAME", "DB_STATUS")
VALUES 
  ('oracle', 'Y'),
  ('postgres', 'Y'),
  ('mysql', 'Y'),
  ('mssql', 'Y')
ON CONFLICT DO NOTHING;

-- Insert a free plan
INSERT INTO "nl2sql_plans" ("plan_name", "plan_description", "price_monthly", "price_yearly", "is_active", "is_free")
VALUES 
  ('Free', 'Basic free plan', 0, 0, TRUE, TRUE)
ON CONFLICT DO NOTHING;
